user_registration_success:
    path: /registration/success
    defaults:
        _controller: \Mindy\Bundle\UserBundle\RegistrationController::success

user_registration_confirm:
    path: /registration/confirm/{token}
    requirements:
        token: \d+
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Registration::confirm

user_set_password:
    path: /set_password/{token}
    requirements:
        token: \d+
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Password::set

user_change_password:
    path: /change_password
    requirements:
        token: \d+
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Password::change

user_registration:
    path: /registration
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Registration::registration

user_login:
    path: /login
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Auth::login

user_logout:
    path: /logout
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\Auth::logout

user_lost_password:
    path: /lost_password
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\LostPassword::lost

user_lost_password_success:
    path: /lost_password/success
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\LostPassword::success

user_lost_password_confirm:
    path: /lost_password/{token}
    defaults:
        _controller: \Mindy\Bundle\UserBundle\UserBundle\LostPassword::confirm
    requirements:
        token: \d+
