services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Mindy\Bundle\UserBundle\:
        resource: '../../*'
        exclude: '../../{Tests,Model,vendor}'

    Mindy\Bundle\UserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Mindy\Bundle\UserBundle\Utils\TokenGenerator:
        public: true
